### ISSUE TITLE
Possible Target of Target for focus?

### ISSUE THREAD

**Issue by ZetoxZ** [wardz/FocusFrame#14]
Is this possible to see your focus's target just like normal unit frame? :D <3 thanks keep up the great work.

Also, I'm able to do what I want with my mouseover focus having 1 macro same button to focus and clear it by doing 
/clearfocus
/mfocus
^^^This is perfect thank you!

**Comment by wardz** [comment]
Focus target was recently added in v1.3.0 by @yutsuku. You can turn it on using `/foption target`.
Keep in mind due to vanilla limitations this frame is only updated when you or someone else in your party have target on the focus unit. (I might add some sort of combat log scanning in the future so u can detect who focus attacked/healed last to guess who the target is, but don't have time for it atm)
